// js/config.js

console.log('Config loaded');

// --- CONSTANTS (from env.js) ---
const SUPABASE_URL = window.ENV?.SUPABASE_URL || 'YOUR_SUPABASE_URL';
const SUPABASE_KEY = window.ENV?.SUPABASE_ANON_KEY || 'YOUR_SUPABASE_ANON_KEY';

// --- EmailJS Config (from env.js) ---
const EMAILJS_PUBLIC_KEY = window.ENV?.EMAILJS_PUBLIC_KEY || 'YOUR_EMAILJS_PUBLIC_KEY';
const EMAILJS_SERVICE_ID = window.ENV?.EMAILJS_SERVICE_ID || 'YOUR_EMAILJS_SERVICE_ID';
const EMAILJS_APPROVAL_TEMPLATE = window.ENV?.EMAILJS_APPROVAL_TEMPLATE || 'YOUR_TEMPLATE_ID';
const EMAILJS_REJECTION_TEMPLATE = window.ENV?.EMAILJS_REJECTION_TEMPLATE || 'YOUR_TEMPLATE_ID';

// --- GLOBAL STATE ---
// We attach these to window so they are accessible by other scripts and HTML attributes
window.supabaseClient = null;
window.equipments = [];
window.currentUser = null;
window.currentFilter = 'all'; // all, available, borrowed, my-items, returns
window.currentCategory = 'all'; // all, Camera, Lens, Audio, Lighting, Accessory
window.currentLang = 'th';
window.isDark = false;

// --- TRANSLATIONS ---
window.translations = {
    th: {
        overview: 'ภาพรวม',
        backToBrowse: 'กลับหน้าหลัก',
        historyGoBack: 'ย้อนกลับ',
        searchPlaceholder: 'ค้นหาอุปกรณ์...',
        all: 'ทั้งหมด',
        available: 'ว่าง',
        borrowed: 'ถูกยืม',
        activeTransactions: 'รายการยืมที่กำลังดำเนินการ',
        equipment: 'อุปกรณ์',
        borrower: 'ผู้ยืม',
        date: 'วันที่',
        status: 'สถานะ',
        action: 'ดำเนินการ',
        borrow: 'ยืมอุปกรณ์',
        edit: 'แก้ไข',
        addEquipment: '+ เพิ่มอุปกรณ์',
        logout: 'ออกจากระบบ',
        totalEquipments: 'อุปกรณ์ทั้งหมด',
        borrowTitle: 'ยืนยันการยืม',
        pleaseEnterName: 'กรุณาระบุชื่อผู้ยืม',
        successBorrow: 'ยืมอุปกรณ์สำเร็จ',
        successReturn: 'คืนอุปกรณ์สำเร็จ',
        successAdd: 'เพิ่มอุปกรณ์สำเร็จ',
        successUpdate: 'อัพเดทข้อมูลสำเร็จ',
        errorUpdate: 'เกิดข้อผิดพลาดในการอัพเดท',
        errorSave: 'เกิดข้อผิดพลาดในการบันทึก',
        errorGeneral: 'เกิดข้อผิดพลาด',
        returnNotify: 'รับคืน',
        outOfStock: 'ของหมด',
        myItems: 'ของฉัน',
        returns: 'แจ้งคืน',
        youHave: 'คุณมี:',
        startDate: 'เริ่ม',
        endDate: 'สิ้นสุด',
        overdue: 'คืนล่าช้า',
        myBorrowings: 'ของที่ฉันยืม',
        noActiveBorrowings: 'ไม่มีรายการยืม',
        dueDate: 'คืนภายใน',
        borrowedOn: 'ยืมเมื่อ',
        alreadyBooked: 'อุปกรณ์ถูกจองแล้ว',
        category: 'ประเภท',
        allCategories: 'ทั้งหมด',
        noActiveTransactions: 'ไม่มีรายการคืน',
        active: 'กำลังยืม',
        refresh: 'รีเฟรช',
        today: 'วันนี้',
        thisWeek: 'สัปดาห์นี้',
        onTimeRate: 'อัตราตรงเวลา',
        weeklyBorrowings: 'การยืมรายสัปดาห์',
        topEquipment: 'อุปกรณ์ยอดนิยม',
        topBorrowers: 'ผู้ยืมมากที่สุด',
        loading: 'กำลังโหลด...',
        noBorrowingData: 'ไม่มีข้อมูลการยืม',
        times: 'ครั้ง',
        // Booking Calendar
        selectDates: 'เลือกวันยืม-คืน',
        dateRequired: 'กรุณาเลือกวันยืม-คืน',
        booked: 'ไม่สามารถทำรายการ',
        selected: 'เลือกไว้',
        requestToBorrow: 'ขอยืมอุปกรณ์',
        useCartToBook: 'ใช้ปุ่มตะกร้าเพื่อยืม',
        equipmentDetails: 'รายละเอียดอุปกรณ์',
        totalDuration: 'ระยะเวลา',
        days: 'วัน',
        // Labels
        search: 'ค้นหา',
        statusLabel: 'สถานะ',
        myBorrowingsDesc: 'รายการอุปกรณ์ที่คุณกำลังยืมอยู่',
        noItemsDesc: 'คุณยังไม่ได้ยืมอุปกรณ์ใดๆ ในขณะนี้',
        browseEquipments: 'เลือกยืมอุปกรณ์',
        daysRemaining: 'วัน',
        // Cart
        dashboard: 'แดชบอร์ด',
        viewDetails: 'ดูรายละเอียด',
        addToCart: 'ใส่ตะกร้า',
        inCart: 'ในตะกร้า',
        cartTitle: 'ตะกร้าอุปกรณ์',
        cartEmpty: 'ตะกร้าว่างเปล่า',
        cartEmptyDesc: 'เลือกอุปกรณ์ที่ต้องการยืม',
        pieces: 'ชิ้น',
        submitRequest: 'ส่งคำขอยืม',
        // Request Form
        selectedEquipments: 'อุปกรณ์ที่เลือก',
        borrowStartDate: 'วันเริ่มยืม',
        returnDate: 'วันคืน',
        noteOptional: 'หมายเหตุ (ไม่บังคับ)',
        notePlaceholder: 'ระบุเหตุผลหรือรายละเอียดเพิ่มเติม...',
        confirmSubmit: 'ยืนยันส่งคำขอ',
        requestSummaryTitle: 'สรุปคำขอยืม',
        requestSummaryHelper: 'ระบบจะตรวจสอบเงื่อนไขก่อนส่งคำขอเพื่อช่วยลดการแก้ไขซ้ำ',
        requestSummaryDuration: 'ระยะเวลายืม',
        requestSummaryItems: 'จำนวนรายการ',
        requestSummaryCategories: 'หมวดหมู่',
        requestRulesTitle: 'เงื่อนไขที่ตรวจสอบ',
        requestSyncNotice: 'วันที่ในแบบฟอร์มจะอัปเดตกลับไปยังตัวกรองอัตโนมัติ',
        requestReady: 'พร้อมส่งคำขอ',
        requestNeedsAttention: 'กรุณาตรวจสอบเงื่อนไขที่ยังไม่ผ่าน',
        requestDateSynced: 'อัปเดตวันที่ในตัวกรองแล้ว',
        requestRuleMaxItems: 'จำนวนรายการไม่เกิน 3 รายการ',
        requestRuleNoWeekend: 'วันยืมและวันคืนต้องไม่ตรงเสาร์-อาทิตย์',
        requestRuleNoCurrentBorrow: 'ไม่มีรายการยืมค้างหรือคำขอรออนุมัติ',
        requestRuleNoCategoryConflict: 'ไม่มีหมวดหมู่ซ้ำกับรายการที่ทับช่วงวัน',
        requestRuleCategoryUnique: 'ในตะกร้าไม่มีหมวดหมู่ซ้ำกัน',
        // My Requests
        myRequests: 'คำขอของฉัน',
        noRequests: 'ยังไม่มีคำขอยืม',
        noRequestsDesc: 'เลือกอุปกรณ์และส่งคำขอเพื่อเริ่มต้น',
        sentOn: 'ส่งเมื่อ',
        deleteRequest: 'ลบคำขอนี้',
        approved: 'อนุมัติแล้ว',
        rejected: 'ถูกปฏิเสธ',
        pendingApproval: 'รออนุมัติ',
        reason: 'เหตุผล',
        // Pending Requests (Admin)
        noPendingRequests: 'ไม่มีคำขอที่รออนุมัติ',
        approveAll: '✓ อนุมัติทั้งหมด',
        pendingCount: 'รอดำเนินการ',
        approve: 'อนุมัติ',
        reject: 'ปฏิเสธ',
        requestAdminSummary: 'สรุปเพื่อช่วยตัดสินใจ',
        requestSubmittedOn: 'ส่งคำขอเมื่อ',
        requestDuration: 'ระยะเวลา',
        requestItemsCount: 'จำนวนอุปกรณ์',
        decisionHint: 'จุดที่ควรตรวจ',
        availabilityReady: 'พร้อมอนุมัติ',
        availabilityLimited: 'สต็อกไม่พอ',
        rejectReasonTitle: 'ปฏิเสธคำขอ',
        rejectReasonHint: 'ระบุเหตุผลสั้น ๆ เพื่อช่วยให้ผู้ใช้แก้ไขได้ถูกจุด',
        rejectReasonPlaceholder: 'เช่น มีอุปกรณ์ไม่พอในช่วงวันดังกล่าว',
        cancel: 'ยกเลิก',
        confirmReject: 'ยืนยันการปฏิเสธ',
        // Toast Messages
        selectEquipmentFirst: 'กรุณาเลือกอุปกรณ์ก่อน',
        selectBorrowDates: 'กรุณาเลือกวันยืม-คืน',
        endDateAfterStart: 'วันสิ้นสุดต้องหลังวันเริ่มต้น',
        weekendNotAllowed: 'ไม่สามารถทำรายการยืมในวันเสาร์-อาทิตย์ได้',
        requestSentSuccess: 'ส่งคำขอยืมสำเร็จ! รอการอนุมัติ',
        requestNotFound: 'ไม่พบคำขอ',
        equipmentNotFound: 'ไม่พบอุปกรณ์',
        confirmDeleteRequest: 'ต้องการลบคำขอนี้หรือไม่?',
        rejectionReasonPrompt: 'เหตุผลที่ปฏิเสธ (ไม่บังคับ):',
        requestRejected: 'คำขอถูกปฏิเสธ',
        daysLeft: 'เหลืออีก',
        dayUnit: 'วัน',
        dueToday: 'ครบกำหนดวันนี้',
        overdueBy: 'เกินกำหนด',
        markAllRead: 'อ่านทั้งหมด',
        // User Profile
        profile: 'ข้อมูลส่วนตัว',
        totalStrikes: 'คะแนนทำผิดเงื่อนไข',
        myHistory: 'ประวัติการยืมของฉัน',
        myHistoryDesc: 'รายการอุปกรณ์ที่เคยทำรายการ',
        strikeUnit: 'ครั้ง',
        penaltyProfileLoading: 'กำลังโหลดข้อมูลผู้ใช้...',
        penaltyCurrentStrikes: 'Strike ปัจจุบัน',
        penaltyProjectedStrikes: 'Strike หลังบันทึก',
        penaltyBanEffect: 'ผลต่อการระงับสิทธิ์',
        penaltyNoBan: 'ยังไม่ถูกระงับสิทธิ์',
        penaltyTemporaryBan: 'ระงับการยืมชั่วคราว',
        penaltyPermanentBan: 'ระงับการยืมถาวร',
        penaltySeverity: 'ระดับความรุนแรง',
        penaltyCompensationStatus: 'สถานะค่าชดใช้',
        penaltyCompensationPending: 'รอชำระ',
        penaltyCompensationNone: 'ไม่มี',
        // Request Success Modal
        requestSuccessTitle: 'ส่งคำขอยืมสำเร็จ!',
        requestSuccessDesc: 'คำขอของคุณถูกส่งเรียบร้อยแล้ว กรุณารอการอนุมัติจากผู้ดูแลระบบ',
        requestSuccessClose: 'ตกลง',
        requestSuccessItems: 'อุปกรณ์',
        requestSuccessDate: 'ช่วงวันที่ยืม',
        // Borrowing Limits
        onlyOnePerCategory: 'ยืมได้เพียงประเภทละ 1 ชิ้นเท่านั้น',
        alreadyHaveCategory: 'คุณมีอุปกรณ์ประเภทนี้ในตะกร้าแล้ว',
        maxBorrowLimit: 'สามารถยืมได้สูงสุด 3 อุปกรณ์ต่อครั้ง',
        mustReturnFirst: 'กรุณาคืนอุปกรณ์ที่ยืมอยู่ก่อนทำรายการใหม่',
        currentlyBorrowing: 'กำลังยืมอยู่',
        pendingRequests: 'รออนุมัติ',
        itemsLabel: 'รายการ',
        cartItemRemoved: 'ถูกลบออกจากตะกร้าเนื่องจากของหมด',
        borrowLimitExceeded: 'เกินจำนวนที่สามารถยืมได้ (สูงสุด 3 รายการ)',
        selectMaxItems: 'กรุณาเลือกอุปกรณ์ไม่เกิน 3 รายการ',
        categoryAlreadyBorrowedForDate: 'ไม่สามารถทำรายการได้ เนื่องจากคุณได้ทำการยืมอุปกรณ์ในหมวดหมู่นี้สำหรับวันดังกล่าวไปแล้ว',
        checkingCategoryConflict: 'กำลังตรวจสอบเงื่อนไขการยืม...',
        manageHelper: 'ตรวจสอบข้อมูลอุปกรณ์ จำนวน และผลกระทบต่อสต็อกก่อนบันทึก',
        manageModeCreate: 'สร้างใหม่',
        manageModeEdit: 'แก้ไขกลุ่มเดิม',
        manageNameLabel: 'ชื่ออุปกรณ์',
        manageTypeLabel: 'ประเภท',
        manageImageLabel: 'รูปภาพ (URL)',
        managePreviewTitle: 'ตัวอย่างรูปภาพ',
        manageImagePreviewEmpty: 'ใส่ URL รูปภาพเพื่อดูตัวอย่างก่อนบันทึก',
        manageQuantityLabel: 'จำนวนที่ต้องการ',
        manageQuantityCreateHint: 'ระบบจะสร้างอุปกรณ์หลายชิ้นด้วยชื่อเดียวกัน',
        manageQuantityEditHint: 'ปรับจำนวนรวมของอุปกรณ์กลุ่มนี้ได้ตามสต็อกที่ว่าง',
        manageSummaryTitle: 'สรุปการเปลี่ยนแปลง',
        manageCurrentQuantity: 'จำนวนปัจจุบัน',
        managePlannedQuantity: 'จำนวนหลังบันทึก',
        manageAvailabilityLabel: 'ว่าง / ถูกยืม',
        manageImpactLabel: 'ผลกระทบ',
        manageReadyCreate: 'พร้อมเพิ่มอุปกรณ์ใหม่',
        manageReadyUpdate: 'พร้อมอัปเดตอุปกรณ์กลุ่มนี้',
        manageNeedsAttention: 'กรุณาแก้ข้อมูลที่ยังไม่ผ่านก่อนบันทึก',
        manageImpactNoChange: 'แก้เฉพาะรายละเอียด โดยไม่เปลี่ยนจำนวน',
        manageImpactIncrease: 'จะเพิ่มอุปกรณ์ใหม่',
        manageImpactDecrease: 'จะลดอุปกรณ์ที่ว่างออก',
        manageImpactBlocked: 'ไม่สามารถลดจำนวนต่ำกว่าจำนวนที่ถูกยืมอยู่',
        manageValidationName: 'กรุณาระบุชื่ออุปกรณ์',
        manageValidationImage: 'กรุณาระบุ URL รูปภาพ',
        manageValidationType: 'กรุณาเลือกประเภทอุปกรณ์',
        manageValidationYear: 'ปีที่ซื้อไม่ถูกต้อง',
        manageValidationQuantity: 'จำนวนต้องอยู่ระหว่าง 1-100',
        manageValidationBorrowedFloor: 'จำนวนหลังบันทึกต้องไม่น้อยกว่าจำนวนที่กำลังถูกยืมอยู่',
        manageDeleteHint: 'การลบทั้งกลุ่มทำได้เมื่ออุปกรณ์ทุกชิ้นยังว่างอยู่เท่านั้น',
        manageDeleteAction: 'ลบอุปกรณ์กลุ่มนี้',
        manageDeleteConfirm: 'ยืนยันลบทั้งกลุ่ม',
        manageDeleteReady: 'ทุกชิ้นว่างอยู่ สามารถลบทั้งกลุ่มได้',
        manageDeleteBlocked: 'ยังมีบางชิ้นถูกยืมอยู่ จึงยังลบทั้งกลุ่มไม่ได้',
        manageDeleteSuccess: 'ลบอุปกรณ์กลุ่มนี้สำเร็จ',
        save: 'บันทึก',
        // Return Modal
        confirmReturnTitle: 'ยืนยันการรับคืน',
        confirmReturnDesc: 'ต้องการรับคืน',
        confirmReturnDescSuffix: 'หรือไม่?',
        confirmReturnCancel: 'ยกเลิก',
        confirmReturnConfirm: 'ยืนยัน',
        returnBorrowerLabel: 'ผู้ยืม',
        returnEquipmentLabel: 'อุปกรณ์',
        returnDecisionTitle: 'สรุปก่อนรับคืน',
        returnDecisionHelper: 'ตรวจสอบสถานะการคืนและเลือกขั้นตอนถัดไปก่อนยืนยัน',
        returnBorrowedOn: 'ยืมเมื่อ',
        returnDueOn: 'กำหนดคืน',
        returnDurationLabel: 'ระยะเวลาที่ยืม',
        returnStatusLabel: 'สถานะปัจจุบัน',
        returnTimingLabel: 'จังหวะการคืน',
        returnChecklistTitle: 'จุดที่ควรตรวจ',
        returnReadyMessage: 'พร้อมปิดรายการรับคืน',
        returnReviewMessage: 'กรุณาตรวจสอบการคืนล่าช้าหรือปัญหาก่อนยืนยัน',
        returnChecklistOnTime: 'รายการนี้อยู่ในช่วงคืนปกติ สามารถปิดรายการได้ทันที',
        returnChecklistOverdue: 'รายการนี้เกินกำหนดคืน ควรพิจารณาบทลงโทษหรือบันทึกหมายเหตุ',
        returnChecklistInspect: 'ตรวจสภาพอุปกรณ์และอุปกรณ์เสริมก่อนยืนยันรับคืน',
        returnChecklistPenalty: 'หากพบความเสียหายหรือคืนไม่ครบชุด ให้เปิดหน้าบทลงโทษก่อน',
        returnPenaltyHint: 'ถ้าพบการคืนล่าช้าหรือความเสียหาย สามารถเปิดฟอร์มบทลงโทษต่อจากหน้านี้ได้ทันที',
        returnPenaltyAction: 'รายงานปัญหา / บทลงโทษ',
        returnDueIn: 'ครบกำหนดอีก',
        // Rejection Notifications
        autoRejectedReason: 'อุปกรณ์ถูกอนุมัติให้ผู้ใช้รายอื่นแล้วในช่วงวันที่ที่ทับซ้อนกัน',
        rejectionEmailSent: 'ส่ง email แจ้งเตือนการปฏิเสธแล้ว',
        autoRejectedNotice: 'คำขอที่ทับซ้อนถูกปฏิเสธอัตโนมัติ',
        autoRejectedCount: 'รายการที่ถูกปฏิเสธอัตโนมัติ',
        // Equipment Age
        purchaseYear: 'ปีที่ซื้อ',
        equipmentAge: 'อายุอุปกรณ์',
        yearUnit: 'ปี',
        purchaseYearHint: 'ระบุปี พ.ศ. หรือ ค.ศ. ที่ซื้ออุปกรณ์',
        ageCalculation: 'อายุการใช้งาน',
        newEquipment: 'อุปกรณ์ใหม่ (ปีนี้)',
        noPurchaseYear: 'ไม่ระบุปีที่ซื้อ',
        dashboardActionFocus: 'กดเพื่อไปยังรายการที่ควรทำต่อมากที่สุด',
        dashboardActionOverdue: 'กดเพื่อเปิดประวัติที่เลยกำหนด',
        dashboardActionPending: 'กดเพื่อเปิดหน้าตรวจคำขอที่รออนุมัติ',
        dashboardActionUtilization: 'กดเพื่อดูอุปกรณ์ที่กำลังถูกยืม',
        dashboardActionTotal: 'กดเพื่อกลับไปดูอุปกรณ์ทั้งหมด',
        dashboardActionAvailable: 'กดเพื่อดูเฉพาะอุปกรณ์พร้อมใช้',
        dashboardActionBorrowed: 'กดเพื่อดูเฉพาะอุปกรณ์ที่ถูกยืม',
        dashboardActionOnTime: 'กดเพื่อเปิดประวัติรายการที่คืนแล้ว',
        dashboardActionTrend: 'กดจุดบนกราฟเพื่อเปิดประวัติของวันนั้น',
        dashboardActionCategory: 'กดส่วนของกราฟหรือชิปเพื่อกรองตามประเภท',
        dashboardActionStatus: 'กดแท่งบนกราฟเพื่อเปิดมุมมองตามสถานะ',
        dashboardActionBorrowers: 'กดแท่งบนกราฟเพื่อเปิดประวัติของผู้ยืมนั้น',
        dashboardActionPenalty: 'กดส่วนของกราฟเพื่อเปิดประวัติบทลงโทษ',
        // History Table
        historyClearFilters: 'ล้างตัวกรอง',
        historyTypeColumn: 'ประเภท',
        historyShowing: 'แสดง',
        historyOf: 'จาก',
        historyRecords: 'รายการ',
        historyStatusActive: 'กำลังยืม',
        historyStatusReturned: 'คืนแล้ว',
        historyStatusOverdue: 'เลยกำหนด',
        historyStatusLate: 'คืนล่าช้า',
        // Penalty History Modal
        penaltyHistoryTitle: 'ประวัติบทลงโทษ',
        penaltyHistorySearch: 'ค้นหาผู้ใช้...',
        penaltyHistoryEmpty: 'ไม่มีประวัติบทลงโทษ',
        penaltyHistoryLateReturn: 'คืนล่าช้า',
        penaltyHistoryNoShow: 'ไม่มารับของ',
        penaltyHistoryMinorDamage: 'เสียหายเล็กน้อย',
        penaltyHistoryMajorDamage: 'เสียหายปานกลาง',
        penaltyHistorySevereDamage: 'เสียหายรุนแรง',
        penaltyHistoryLost: 'สูญหาย',
        penaltyHistoryCompPaid: 'ชำระแล้ว',
        penaltyHistoryCompPending: 'รอชำระ',
        // Equipment Browse
        equipmentLoading: 'กำลังโหลดอุปกรณ์...'
    },
    en: {
        overview: 'Overview',
        backToBrowse: 'Back to Browse',
        historyGoBack: 'Go Back',
        searchPlaceholder: 'Search equipment...',
        all: 'All',
        available: 'Available',
        borrowed: 'Borrowed',
        activeTransactions: 'Active Transactions',
        equipment: 'Equipment',
        borrower: 'Borrower',
        date: 'Date',
        status: 'Status',
        action: 'Action',
        borrow: 'Borrow',
        edit: 'Edit',
        addEquipment: '+ Add Equipment',
        logout: 'Logout',
        totalEquipments: 'Total Equipments',
        borrowTitle: 'Confirm Borrow',
        pleaseEnterName: 'Please enter borrower name',
        successBorrow: 'Borrowed successfully',
        successReturn: 'Returned successfully',
        successAdd: 'Added successfully',
        successUpdate: 'Updated successfully',
        errorUpdate: 'Error updating',
        errorSave: 'Error saving',
        errorGeneral: 'An error occurred',
        returnNotify: 'Return',
        outOfStock: 'Out of Stock',
        myItems: 'My Items',
        returns: 'Returns',
        youHave: 'You have:',
        startDate: 'Start',
        endDate: 'End',
        overdue: 'Overdue',
        myBorrowings: 'My Borrowings',
        noActiveBorrowings: 'No active borrowings',
        dueDate: 'Due',
        borrowedOn: 'Borrowed on',
        alreadyBooked: 'Equipment already booked',
        category: 'Category',
        allCategories: 'All',
        noActiveTransactions: 'No active transactions',
        active: 'Active',
        refresh: 'Refresh',
        today: 'Today',
        thisWeek: 'This Week',
        onTimeRate: 'On-Time Rate',
        weeklyBorrowings: 'Weekly Borrowings',
        topEquipment: 'Top Equipment',
        topBorrowers: 'Top Borrowers',
        loading: 'Loading...',
        noBorrowingData: 'No borrowing data',
        times: 'times',
        // Booking Calendar
        selectDates: 'Select Dates',
        dateRequired: 'Please select borrow dates',
        booked: 'Booked',
        selected: 'Selected',
        requestToBorrow: 'Request to Borrow',
        useCartToBook: 'Use the cart button to borrow',
        equipmentDetails: 'Equipment Details',
        totalDuration: 'Duration',
        days: 'days',
        // Labels
        search: 'Search',
        statusLabel: 'Status',
        myBorrowingsDesc: 'Equipment you are currently borrowing',
        noItemsDesc: 'You have not borrowed any equipment yet',
        browseEquipments: 'Browse Equipment',
        daysRemaining: 'days',
        // Cart
        dashboard: 'Dashboard',
        viewDetails: 'View Details',
        addToCart: 'Add to Cart',
        inCart: 'In Cart',
        cartTitle: 'Equipment Cart',
        cartEmpty: 'Cart is empty',
        cartEmptyDesc: 'Select equipment to borrow',
        pieces: 'pcs',
        submitRequest: 'Submit Request',
        // Request Form
        selectedEquipments: 'Selected Equipment',
        borrowStartDate: 'Start Date',
        returnDate: 'Return Date',
        noteOptional: 'Note (Optional)',
        notePlaceholder: 'Specify reason or additional details...',
        confirmSubmit: 'Confirm & Submit',
        requestSummaryTitle: 'Request Summary',
        requestSummaryHelper: 'The system checks key rules before submission to reduce retrying the flow.',
        requestSummaryDuration: 'Borrow duration',
        requestSummaryItems: 'Items',
        requestSummaryCategories: 'Categories',
        requestRulesTitle: 'Rules checked',
        requestSyncNotice: 'Dates in this form will sync back to the filter automatically.',
        requestReady: 'Ready to submit',
        requestNeedsAttention: 'Please fix the remaining issues before submitting',
        requestDateSynced: 'Filter dates updated',
        requestRuleMaxItems: 'No more than 3 items per request',
        requestRuleNoWeekend: 'Borrow and return dates must not fall on weekends',
        requestRuleNoCurrentBorrow: 'No active borrowings or pending requests',
        requestRuleNoCategoryConflict: 'No overlapping category conflict for the selected dates',
        requestRuleCategoryUnique: 'No duplicate categories in the cart',
        // My Requests
        myRequests: 'My Requests',
        noRequests: 'No requests yet',
        noRequestsDesc: 'Select equipment and submit a request to get started',
        sentOn: 'Sent on',
        deleteRequest: 'Delete this request',
        approved: 'Approved',
        rejected: 'Rejected',
        pendingApproval: 'Pending',
        reason: 'Reason',
        // Pending Requests (Admin)
        noPendingRequests: 'No pending requests',
        approveAll: '✓ Approve All',
        pendingCount: 'pending',
        approve: 'Approve',
        reject: 'Reject',
        requestAdminSummary: 'Decision support summary',
        requestSubmittedOn: 'Submitted on',
        requestDuration: 'Duration',
        requestItemsCount: 'Items',
        decisionHint: 'Check first',
        availabilityReady: 'Ready to approve',
        availabilityLimited: 'Limited stock',
        rejectReasonTitle: 'Reject request',
        rejectReasonHint: 'Add a short reason so the user knows what to fix.',
        rejectReasonPlaceholder: 'e.g. Equipment is unavailable for the selected dates',
        cancel: 'Cancel',
        confirmReject: 'Confirm Reject',
        // Toast Messages
        selectEquipmentFirst: 'Please select equipment first',
        selectBorrowDates: 'Please select borrow dates',
        endDateAfterStart: 'End date must be after start date',
        weekendNotAllowed: 'Borrowing is not allowed on weekends (Saturday-Sunday)',
        requestSentSuccess: 'Request sent successfully! Awaiting approval',
        requestNotFound: 'Request not found',
        equipmentNotFound: 'Equipment not found',
        confirmDeleteRequest: 'Delete this request?',
        rejectionReasonPrompt: 'Reason for rejection (optional):',
        requestRejected: 'Request rejected',
        daysLeft: 'left',
        dayUnit: 'days',
        dueToday: 'Due today',
        overdueBy: 'Overdue by',
        markAllRead: 'Mark all read',
        // User Profile
        profile: 'My Profile',
        totalStrikes: 'Total Strikes',
        myHistory: 'My Borrowing History',
        myHistoryDesc: 'Equipment you have previously borrowed',
        strikeUnit: 'strikes',
        profileBackBtn: 'Back to Browse',
        penaltyProfileLoading: 'Loading user profile...',
        penaltyCurrentStrikes: 'Current strikes',
        penaltyProjectedStrikes: 'Projected strikes',
        penaltyBanEffect: 'Borrowing restriction',
        penaltyNoBan: 'No borrowing ban',
        penaltyTemporaryBan: 'Temporary borrowing ban',
        penaltyPermanentBan: 'Permanent borrowing ban',
        penaltySeverity: 'Severity',
        penaltyCompensationStatus: 'Compensation',
        penaltyCompensationPending: 'Pending payment',
        penaltyCompensationNone: 'None',
        // Request Success Modal
        requestSuccessTitle: 'Request Submitted!',
        requestSuccessDesc: 'Your request has been submitted successfully. Please wait for admin approval.',
        requestSuccessClose: 'OK',
        requestSuccessItems: 'Equipment',
        requestSuccessDate: 'Borrow Period',
        // Borrowing Limits
        onlyOnePerCategory: 'Only 1 item per category allowed',
        alreadyHaveCategory: 'You already have this category in your cart',
        maxBorrowLimit: 'Maximum 3 items per borrow request',
        mustReturnFirst: 'Please return your current items before borrowing again',
        currentlyBorrowing: 'Currently borrowing',
        pendingRequests: 'Pending requests',
        itemsLabel: 'items',
        cartItemRemoved: 'removed from cart (out of stock)',
        borrowLimitExceeded: 'Exceeds borrow limit (max 3 items)',
        selectMaxItems: 'Please select no more than 3 items',
        categoryAlreadyBorrowedForDate: 'Cannot proceed — you have already borrowed equipment in this category for the selected date',
        checkingCategoryConflict: 'Checking borrow eligibility...',
        manageHelper: 'Review the equipment details, quantity, and stock impact before saving.',
        manageModeCreate: 'New item',
        manageModeEdit: 'Editing group',
        manageNameLabel: 'Equipment name',
        manageTypeLabel: 'Type',
        manageImageLabel: 'Image URL',
        managePreviewTitle: 'Image preview',
        manageImagePreviewEmpty: 'Add an image URL to preview it before saving',
        manageQuantityLabel: 'Planned quantity',
        manageQuantityCreateHint: 'This will create multiple equipment units with the same name',
        manageQuantityEditHint: 'Adjust the total quantity for this equipment group based on available stock',
        manageSummaryTitle: 'Change summary',
        manageCurrentQuantity: 'Current quantity',
        managePlannedQuantity: 'Planned quantity',
        manageAvailabilityLabel: 'Available / borrowed',
        manageImpactLabel: 'Impact',
        manageReadyCreate: 'Ready to add new equipment',
        manageReadyUpdate: 'Ready to update this equipment group',
        manageNeedsAttention: 'Please fix the remaining issues before saving',
        manageImpactNoChange: 'Only the details will change; quantity stays the same',
        manageImpactIncrease: 'Will add new equipment units',
        manageImpactDecrease: 'Will remove available equipment units',
        manageImpactBlocked: 'Cannot reduce below the number of borrowed units',
        manageValidationName: 'Please enter the equipment name',
        manageValidationImage: 'Please enter the image URL',
        manageValidationType: 'Please select the equipment type',
        manageValidationYear: 'Purchase year is invalid',
        manageValidationQuantity: 'Quantity must be between 1 and 100',
        manageValidationBorrowedFloor: 'The planned quantity cannot be lower than the number of borrowed units',
        manageDeleteHint: 'Deleting the whole group is only available when every unit is currently available.',
        manageDeleteAction: 'Delete this equipment group',
        manageDeleteConfirm: 'Confirm delete group',
        manageDeleteReady: 'All units are available, so this group can be deleted safely.',
        manageDeleteBlocked: 'Some units are still borrowed, so this group cannot be deleted yet.',
        manageDeleteSuccess: 'Equipment group deleted successfully',
        save: 'Save',
        // Return Modal
        confirmReturnTitle: 'Confirm Return',
        confirmReturnDesc: 'Mark',
        confirmReturnDescSuffix: 'as returned?',
        confirmReturnCancel: 'Cancel',
        confirmReturnConfirm: 'Confirm',
        returnBorrowerLabel: 'Borrower',
        returnEquipmentLabel: 'Equipment',
        returnDecisionTitle: 'Return summary',
        returnDecisionHelper: 'Review the return status and choose the next action before closing this transaction.',
        returnBorrowedOn: 'Borrowed on',
        returnDueOn: 'Due on',
        returnDurationLabel: 'Borrow duration',
        returnStatusLabel: 'Current status',
        returnTimingLabel: 'Return timing',
        returnChecklistTitle: 'Check first',
        returnReadyMessage: 'Ready to close this return',
        returnReviewMessage: 'Please review the overdue state or issues before confirming',
        returnChecklistOnTime: 'This item is still within its normal return window and can be closed now.',
        returnChecklistOverdue: 'This item is overdue. Consider a penalty or add context before closing it.',
        returnChecklistInspect: 'Inspect the equipment and accessories before confirming the return.',
        returnChecklistPenalty: 'If anything is damaged or missing, open the penalty flow before closing.',
        returnPenaltyHint: 'If the return is late or the equipment has issues, you can open the penalty form directly from here.',
        returnPenaltyAction: 'Report issue / penalty',
        returnDueIn: 'Due in',
        // Rejection Notifications
        autoRejectedReason: 'Equipment was approved for another user in the overlapping period',
        rejectionEmailSent: 'Rejection notification email sent',
        autoRejectedNotice: 'Overlapping requests auto-rejected',
        autoRejectedCount: 'auto-rejected requests',
        // Equipment Age
        purchaseYear: 'Purchase Year',
        equipmentAge: 'Equipment Age',
        yearUnit: 'years',
        purchaseYearHint: 'Enter the year the equipment was purchased',
        ageCalculation: 'Age',
        newEquipment: 'New (this year)',
        noPurchaseYear: 'Purchase year not specified',
        dashboardActionFocus: 'Click to open the most relevant next step',
        dashboardActionOverdue: 'Click to open overdue borrowing history',
        dashboardActionPending: 'Click to review pending requests',
        dashboardActionUtilization: 'Click to view borrowed equipment',
        dashboardActionTotal: 'Click to return to all equipment',
        dashboardActionAvailable: 'Click to view only available equipment',
        dashboardActionBorrowed: 'Click to view only borrowed equipment',
        dashboardActionOnTime: 'Click to open returned-item history',
        dashboardActionTrend: 'Click a point to open that day\'s history',
        dashboardActionCategory: 'Click a chart segment or chip to filter by category',
        dashboardActionStatus: 'Click a bar to open the matching status view',
        dashboardActionBorrowers: 'Click a bar to open history for that borrower',
        dashboardActionPenalty: 'Click a chart segment to open penalty history',
        // History Table
        historyClearFilters: 'Clear filters',
        historyTypeColumn: 'Type',
        historyShowing: 'Showing',
        historyOf: 'of',
        historyRecords: 'records',
        historyStatusActive: 'Active',
        historyStatusReturned: 'Returned',
        historyStatusOverdue: 'Overdue',
        historyStatusLate: 'Late return',
        // Penalty History Modal
        penaltyHistoryTitle: 'Penalty History',
        penaltyHistorySearch: 'Search user...',
        penaltyHistoryEmpty: 'No penalty records',
        penaltyHistoryLateReturn: 'Late return',
        penaltyHistoryNoShow: 'No-show',
        penaltyHistoryMinorDamage: 'Minor damage',
        penaltyHistoryMajorDamage: 'Major damage',
        penaltyHistorySevereDamage: 'Severe damage',
        penaltyHistoryLost: 'Lost',
        penaltyHistoryCompPaid: 'Paid',
        penaltyHistoryCompPending: 'Pending',
        // Equipment Browse
        equipmentLoading: 'Loading equipment...'
    }
};

// --- INITIALIZATION HELPERS ---
window.initSupabase = function () {
    if (SUPABASE_URL.startsWith('YOUR') || SUPABASE_KEY.startsWith('YOUR')) {
        console.warn('Configuration Needed');
        document.getElementById('loginSection').classList.remove('hidden');
        document.getElementById('loginSection').innerHTML = `
             <div class="fixed inset-0 z-50 flex items-center justify-center bg-gray-100 dark:bg-gray-900">
                 <div class="bg-white p-8 rounded-2xl shadow-xl w-full max-w-md dark:bg-gray-800 text-center">
                     <h2 class="text-2xl font-bold text-red-500 mb-4">Configuration Needed</h2>
                     <p class="text-gray-600 dark:text-gray-300 mb-4">Please set SUPABASE_URL and SUPABASE_KEY in js/config.js</p>
                 </div>
             </div>
         `;
        return false;
    }
    try {
        window.supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_KEY);
        return true;
    } catch (e) {
        console.error("Supabase init failed", e);
        return false;
    }
};
