-- DANGER: This script will WIPE ALL DATA and reset everything.

-- 1. Drop existing tables (Order matters due to foreign keys)
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS equipments;
DROP TABLE IF EXISTS users;

-- 2. Create Users Table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('admin', 'user')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Create Equipments Table
CREATE TABLE equipments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    image_url TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('available', 'borrowed')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Create Transactions Table (With Date-Based Booking Support)
CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_id BIGINT REFERENCES equipments(id),
    borrower_name TEXT NOT NULL,
    borrow_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    return_date TIMESTAMP WITH TIME ZONE,
    start_date TIMESTAMP WITH TIME ZONE, -- New: For finding overlaps
    end_date TIMESTAMP WITH TIME ZONE,   -- New: For finding overlaps
    status TEXT NOT NULL CHECK (status IN ('active', 'returned'))
);

-- 5. Enable RLS (Security)
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE equipments ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;

-- 6. Create Public Access Policies (For Demo/Dev only)
CREATE POLICY "Public read users" ON users FOR SELECT USING (true);
CREATE POLICY "Public access equipments" ON equipments FOR ALL USING (true);
CREATE POLICY "Public access transactions" ON transactions FOR ALL USING (true);

-- 7. Seed Initial Data
-- Users
INSERT INTO users (username, password, role) VALUES
('admin', 'admin123', 'admin'),
('user', 'user123', 'user');

-- Equipments
INSERT INTO equipments (name, type, image_url, status) VALUES
('Sony A7III', 'Camera', 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=500&q=60', 'available'),
('Sony A7III', 'Camera', 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=500&q=60', 'available'),
('Canon EF 50mm', 'Lens', 'https://images.unsplash.com/photo-1617005082133-548c4dd27f35?auto=format&fit=crop&w=500&q=60', 'available'),
('Rode VideoMic', 'Audio', 'https://images.unsplash.com/photo-1590845947698-8924d7409b56?auto=format&fit=crop&w=500&q=60', 'available'),
('Aputure 120d', 'Lighting', 'https://images.unsplash.com/photo-1524368535928-5b5b1c0b16a4?auto=format&fit=crop&w=500&q=60', 'available');
