-- 1. Create the users table if it doesn't exist
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL, -- In a real app, use encryption!
    role TEXT NOT NULL CHECK (role IN ('admin', 'user')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

-- 3. Create a policy to allow anyone to read users (needed for this simple login)
-- WARNING: This exposes user data. For production, use Supabase Auth.
DROP POLICY IF EXISTS "Public read access" ON users;
CREATE POLICY "Public read access" ON users FOR SELECT USING (true);

-- 4. Insert default users (Admin and User)
INSERT INTO users (username, password, role)
VALUES 
    ('admin', 'admin123', 'admin'),
    ('user', 'user123', 'user')
ON CONFLICT (username) DO NOTHING;
